In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import  SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits = load_digits()

In [ ]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [ ]:
from sklearn.model_selection import  train_test_split
train_x, test_x, train_y , test_y = train_test_split(digits.data , digits.target , random_state=56 , stratify=digits.target)

In [ ]:
Lr = LogisticRegression()
Lr.fit(train_x, train_y)
Lr.score(test_x, test_y)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9511111111111111

In [ ]:
svm = SVC()
svm.fit(train_x, train_y)
svm.score(test_x, test_y)


0.9911111111111112

In [ ]:
rf = RandomForestClassifier()
rf.fit(train_x , train_y)
rf.score(test_x, test_y)


0.9755555555555555

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
#method to calculate the score
def get_score(model , train_x , test_x, train_y , test_y):
  model.fit(train_x , train_y)
  sc = model.score(test_x,test_y)
  return sc


In [ ]:
from sklearn.model_selection import  StratifiedKFold
St = StratifiedKFold(n_splits=3)

In [ ]:
score_l =[]
score_svm =[]
score_rf = []

for train_index , test_index in kf.split(digits.data):
  train_x, test_x, train_y,test_y = digits.data[train_index], digits.data[test_index] , digits.target[train_index] , digits.target[test_index]
  score_l.append(get_score(LogisticRegression(),train_x,test_x,train_y,test_y))
  score_svm.append(get_score(SVC() , train_x, test_x, train_y , test_y))
  score_rf.append(get_score(RandomForestClassifier(), train_x, test_x, train_y,test_y))




/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
import numpy as np

np.median(score_l)

0.9232053422370617

In [ ]:
np.median(score_rf)

0.9382303839732888

In [ ]:
np.median(score_svm)

0.9666110183639399

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
score_list = cross_val_score(LogisticRegression(), digits.data , digits.target)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
np.median(score_list) 

0.9222222222222223

In [ ]:
score_random = cross_val_score(RandomForestClassifier() , digits.data , digits.target)

In [ ]:
np.median(score_random) 

0.9277777777777778

In [ ]:
score_svc = cross_val_score(SVC() , digits.data , digits.target)

In [ ]:
np.median(score_svc) 

0.9611111111111111

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [ ]:
from sklearn.model_selection import  cross_val_score , train_test_split
train_x, test_x ,train_y , test_y = train_test_split(iris.data , iris.target , random_state = 56 , test_size=0.25)

In [ ]:
l1 = cross_val_score(LogisticRegression() , iris.data , iris.target)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
np.median(l1)

0.9666666666666667

In [ ]:
l2 = cross_val_score(RandomForestClassifier() , iris.data , iris.target)

In [ ]:
np.median(l2)

0.9666666666666667

In [ ]:
l3 = cross_val_score(SVC() , iris.data , iris.target)
np.median(l3)

0.9666666666666667