In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model 
%matplotlib inline

In [ ]:
df = pd.read_csv('homeprices.csv')

In [ ]:
df.head()


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math


In [ ]:
df.bedrooms.fillna(value=math.floor(df.bedrooms.median()) , inplace=True)

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg = linear_model.LinearRegression()


In [ ]:
reg.fit(df[['area' , 'bedrooms' ,'age']] , df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.predict([[5000,6,2]])


array([915505.05622645])

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

#Exercise

In [ ]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
#df['experience'].replace({'five':5 ,'two':2 ,'seven':7,'three':3,'ten':10,'eleven':11} , inplace=True )

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
df['experience'].fillna(math.floor(df['experience'].median()) , inplace=True)

In [ ]:
df['test_score(out of 10)'].fillna(math.floor(df['test_score(out of 10)'].median()) , inplace=True)

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience' ,'test_score(out of 10)' ,'interview_score(out of 10)']] , df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.predict([[10,8,7]])

array([71154.47154472])

In [ ]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [ ]:
reg.intercept_

11869.91869918695

#Gradient descent Algorithm

In [ ]:
df = pd.read_csv('test_scores.csv')

In [ ]:
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73